# Generated by Django 5.1.7 on 2025-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiAffectingfactors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('harmonic_coefficient', models.FloatField(blank=True, null=True)),
                ('liquid_temperature', models.FloatField(blank=True, null=True)),
                ('pressure_change_rate', models.FloatField(blank=True, null=True)),
                ('temperature_change', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Влияющие факторы',
                'verbose_name_plural': 'Влияющие факторы',
                'db_table': 'si_affectingfactors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiMeasurementtype',
            fields=[
                ('id_measurement_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('error_uncertainty', models.CharField(blank=True, max_length=100, null=True)),
                ('measurement_range', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Вид измерений',
                'verbose_name_plural': 'Виды измерений',
                'db_table': 'si_measurementtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiReference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Эталон',
                'verbose_name_plural': 'Эталоны',
                'db_table': 'si_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiSi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=100)),
                ('manufacture_year', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Средство измерений',
                'verbose_name_plural': 'Средства измерений',
                'db_table': 'si_si',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiSitype',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('reg_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип СИ',
                'verbose_name_plural': 'Типы СИ',
                'db_table': 'si_sitype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiVerificationmethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('doc_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Методика поверки',
                'verbose_name_plural': 'Методики поверки',
                'db_table': 'si_verificationmethod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiVerificationtype',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип поверки',
                'verbose_name_plural': 'Типы поверки',
                'db_table': 'si_verificationtype',
                'managed': False,
            },
        ),
    ]
