# Generated by Django 5.1.7 on 2025-04-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectingFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.FloatField(verbose_name='Влажность')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид измерений',
                'verbose_name_plural': 'Виды измерений',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название эталона')),
                ('registration_number', models.CharField(max_length=50, verbose_name='Рег. номер')),
            ],
        ),
        migrations.CreateModel(
            name='SIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('reg_number', models.CharField(max_length=50, verbose_name='Рег. номер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Методика')),
                ('doc_number', models.CharField(max_length=50, verbose_name='Номер документа')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип поверки')),
            ],
        ),
        migrations.CreateModel(
            name='SI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('manufacture_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='si.sitype', verbose_name='Тип СИ')),
            ],
        ),
    ]
