# Generated by Django 5.1.7 on 2025-04-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectingfactors',
            options={'verbose_name': 'Влияющие факторы', 'verbose_name_plural': 'Влияющие факторы'},
        ),
        migrations.AddField(
            model_name='affectingfactors',
            name='frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Частота сети (Гц)'),
        ),
        migrations.AddField(
            model_name='affectingfactors',
            name='harmonic_coefficient',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент гармоник (%)'),
        ),
        migrations.AddField(
            model_name='affectingfactors',
            name='liquid_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура жидкости (°C)'),
        ),
        migrations.AddField(
            model_name='affectingfactors',
            name='pressure_change_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость изменения давления (гПа/мин)'),
        ),
        migrations.AddField(
            model_name='affectingfactors',
            name='temperature_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение температуры (°C)'),
        ),
        migrations.AddField(
            model_name='affectingfactors',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Напряжение сети (В)'),
        ),
        migrations.AlterField(
            model_name='affectingfactors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='affectingfactors',
            name='humidity',
            field=models.FloatField(default=50.0, verbose_name='Относительная влажность (%)'),
        ),
        migrations.AlterField(
            model_name='affectingfactors',
            name='pressure',
            field=models.FloatField(default=760.0, verbose_name='Атмосферное давление (мм рт. ст.)'),
        ),
        migrations.AlterField(
            model_name='affectingfactors',
            name='temperature',
            field=models.FloatField(default=20.0, verbose_name='Температура воздуха (°C)'),
        ),
    ]
