# Generated by Django 5.1.7 on 2025-04-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sisi',
            table='si',
        ),
    ]
