# Generated by Django 5.1.7 on 2025-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0002_alter_affectingfactors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtype',
            name='error_uncertainty',
            field=models.CharField(max_length=100, null=True, verbose_name='Погрешность/неопределенность'),
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='id_measurement_type',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Код типа измерений'),
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='measurement_range',
            field=models.CharField(default='Not specified', max_length=100, verbose_name='Диапазон измерений'),
            preserve_default=False,
        ),
    ]
