# Generated by Django 5.1.7 on 2025-04-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0003_measurementtype_error_uncertainty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='id_measurement_type',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
