# Generated by Django 5.1.7 on 2025-04-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0003_alter_siverificationtype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='siverificationtype',
            table='verification_types',
        ),
    ]
