# Generated by Django 5.1.7 on 2025-04-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0004_alter_siverificationtype_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siaffectingfactors',
            options={'verbose_name': 'Влияющие факторы', 'verbose_name_plural': 'Влияющие факторы'},
        ),
        migrations.AlterModelOptions(
            name='simeasurementtype',
            options={'verbose_name': 'Вид измерений', 'verbose_name_plural': 'Виды измерений'},
        ),
        migrations.AlterModelOptions(
            name='sireference',
            options={'verbose_name': 'Эталон', 'verbose_name_plural': 'Эталоны'},
        ),
        migrations.AlterModelOptions(
            name='sisi',
            options={'verbose_name': 'Средство измерений', 'verbose_name_plural': 'Средства измерений'},
        ),
        migrations.AlterModelOptions(
            name='sisitype',
            options={'verbose_name': 'Тип СИ', 'verbose_name_plural': 'Типы СИ'},
        ),
        migrations.AlterModelOptions(
            name='siverificationmethod',
            options={'verbose_name': 'Методика поверки', 'verbose_name_plural': 'Методики поверки'},
        ),
        migrations.AlterModelOptions(
            name='siverificationtype',
            options={'verbose_name': 'Тип поверки', 'verbose_name_plural': 'Типы поверки'},
        ),
    ]
