# Generated by Django 5.1.7 on 2025-04-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0005_alter_siaffectingfactors_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE affecting_factors
            ADD COLUMN temperature VARCHAR(255),
            ADD COLUMN humidity VARCHAR(255),
            ADD COLUMN pressure VARCHAR(255),
            ADD COLUMN voltage VARCHAR(255),
            ADD COLUMN frequency VARCHAR(255),
            ADD COLUMN harmonic_coefficient VARCHAR(255),
            ADD COLUMN liquid_temperature VARCHAR(255),
            ADD COLUMN temperature_change VARCHAR(255),
            ADD COLUMN pressure_change_rate VARCHAR(255);
            """,
            reverse_sql="""
            ALTER TABLE affecting_factors
            DROP COLUMN temperature,
            DROP COLUMN humidity,
            DROP COLUMN pressure,
            DROP COLUMN voltage,
            DROP COLUMN frequency,
            DROP COLUMN harmonic_coefficient,
            DROP COLUMN liquid_temperature,
            DROP COLUMN temperature_change,
            DROP COLUMN pressure_change_rate;
            """
        ),
    ]
