# Generated by Django 5.1.7 on 2025-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0006_auto_20250429_2036'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "references"
            ADD COLUMN name VARCHAR(255),
            ADD COLUMN description TEXT;
            
            UPDATE "references"
            SET name = note
            WHERE note IS NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE "references"
            DROP COLUMN name,
            DROP COLUMN description;
            """
        ),
    ] 