# Generated by Django 5.1.7 on 2025-04-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0007_auto_20250429_2039'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "references"
            ADD COLUMN factory_number VARCHAR(255);
            """,
            reverse_sql="""
            ALTER TABLE "references"
            DROP COLUMN factory_number;
            """
        ),
    ] 