# Generated by Django 5.1.7 on 2025-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0011_add_affecting_factors_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sisi',
            name='measurement_range',
        ),
        migrations.AddField(
            model_name='siverificationtype',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
    ]
