version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: vnikti2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    container_name: diplomtest-container
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=vnikti2
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1111
      - DJANGO_SETTINGS_MODULE=diplomtest.settings
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DJANGO_DEBUG=True
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
  static_volume: