# Generated by Django 5.1.7 on 2025-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='Место рождения')),
                ('snils', models.CharField(max_length=14, unique=True, verbose_name='СНИЛС')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Специализация')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='Квалификация')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Вид измерений сотрудника',
                'verbose_name_plural': 'Виды измерений сотрудников',
            },
        ),
    ]
