# Generated by Django 5.1.7 on 2025-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesEmployee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(max_length=255)),
                ('snils', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=254)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeesEmployeemeasurementtype',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measurement_type_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Вид измерений сотрудника',
                'verbose_name_plural': 'Виды измерений сотрудников',
                'db_table': 'employees_employeemeasurementtype',
                'managed': False,
            },
        ),
    ]
