# Generated by Django 5.1.7 on 2025-04-23 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('si', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeemeasurementtype',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_measurement_types', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeemeasurementtype',
            name='measurement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_measurement_types', to='si.measurementtype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='measurement_types',
            field=models.ManyToManyField(related_name='employees', through='employees.EmployeeMeasurementType', to='si.measurementtype', verbose_name='Виды измерений'),
        ),
        migrations.AlterUniqueTogether(
            name='employeemeasurementtype',
            unique_together={('employee', 'measurement_type')},
        ),
    ]
