# Generated by Django 5.1.7 on 2025-04-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesCertificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gov_reg_number', models.CharField(max_length=20)),
                ('inventory_number', models.CharField(max_length=50)),
                ('modification', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('number', models.CharField(max_length=50, unique=True)),
                ('verification_date', models.DateField()),
                ('interval', models.IntegerField()),
                ('next_verification_date', models.DateField()),
                ('verification_result', models.CharField(max_length=7)),
                ('previous_verification_mark', models.CharField(max_length=100)),
                ('is_vn', models.BooleanField()),
                ('mark_in_passport', models.BooleanField()),
                ('mark_on_si', models.BooleanField()),
                ('organization_name', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=12)),
                ('department_head', models.CharField(max_length=100)),
                ('composition', models.TextField()),
                ('comment', models.TextField()),
                ('protocol', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Свидетельство о поверке',
                'verbose_name_plural': 'Свидетельства о поверке',
                'db_table': 'certificates_certificate',
                'ordering': ['-verification_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificatesSiverification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Применение эталона',
                'verbose_name_plural': 'Применения эталонов',
                'db_table': 'certificates_siverification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificatesVerificationmethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('doc_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Методика поверки',
                'verbose_name_plural': 'Методики поверки',
                'db_table': 'certificates_verificationmethod',
                'managed': False,
            },
        ),
    ]
