# Generated by Django 5.1.7 on 2025-04-23 15:22

import certificates.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('si', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата применения')),
            ],
            options={
                'verbose_name': 'Применение эталона',
                'verbose_name_plural': 'Применения эталонов',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_reg_number', models.CharField(default='GOS-0000', max_length=20, verbose_name='Гос. реестр')),
                ('inventory_number', models.CharField(default='INV-0000', max_length=50, verbose_name='Инв. номер')),
                ('modification', models.CharField(blank=True, max_length=100, verbose_name='Модификация')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('number', models.CharField(default=certificates.models.generate_cert_number, max_length=50, unique=True, verbose_name='Номер свидетельства')),
                ('verification_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения поверки')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Интервал поверки (лет)')),
                ('next_verification_date', models.DateField(verbose_name='Срок действия поверки')),
                ('verification_result', models.CharField(choices=[('full', 'В полном объеме'), ('partial', 'В неполном объеме')], default='full', max_length=7, verbose_name='Результат поверки')),
                ('previous_verification_mark', models.CharField(blank=True, max_length=100, verbose_name='Клеймо предыдущей поверки')),
                ('is_vn', models.BooleanField(default=False, verbose_name='СИ ВН')),
                ('mark_in_passport', models.BooleanField(default=False, verbose_name='Знак в паспорте')),
                ('mark_on_si', models.BooleanField(default=False, verbose_name='Знак на СИ')),
                ('organization_name', models.CharField(default='ВНИКТИ', max_length=100, verbose_name='Организация')),
                ('inn', models.CharField(default='5022067103', max_length=12, verbose_name='ИНН')),
                ('department_head', models.CharField(default='Крюков Сергей Александрович', max_length=100, verbose_name='Начальник отдела')),
                ('composition', models.TextField(blank=True, verbose_name='В составе')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('affecting_factors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_affecting', to='si.affectingfactors', verbose_name='Влияющие факторы')),
                ('factors', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_factors', to='si.affectingfactors', verbose_name='Основные факторы')),
                ('si', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='si.si', verbose_name='Средство измерений')),
                ('verification_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='si.verificationmethod', verbose_name='Методика поверки')),
                ('verification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='si.verificationtype', verbose_name='Вид поверки')),
            ],
            options={
                'verbose_name': 'Свидетельство о поверке',
                'verbose_name_plural': 'Свидетельства о поверке',
                'ordering': ['-verification_date'],
            },
        ),
    ]
