# Generated by Django 5.1.7 on 2025-04-23 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('si', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Поверитель'),
        ),
        migrations.AddField(
            model_name='siverification',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate', verbose_name='Свидетельство'),
        ),
        migrations.AddField(
            model_name='siverification',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.reference', verbose_name='Эталон'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='applied_standards',
            field=models.ManyToManyField(through='certificates.SIVerification', to='si.reference', verbose_name='Примененные эталоны'),
        ),
    ]
