# Generated by Django 5.1.7 on 2025-04-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
        ('si', '0002_alter_affectingfactors_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='factors',
        ),
        migrations.CreateModel(
            name='VerificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название методики')),
                ('verification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.verificationtype', verbose_name='Тип поверки')),
            ],
        ),
    ]
