# Generated by Django 5.1.7 on 2025-04-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_certificate_factors_verificationmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='protocol',
            field=models.FileField(blank=True, null=True, upload_to='protocols/', verbose_name='Протокол'),
        ),
    ]
