# Generated by Django 5.1.7 on 2025-04-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('si', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(auto_now_add=True, verbose_name='Дата измерения')),
                ('affecting_factors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si.affectingfactors', verbose_name='Факторы влияния')),
            ],
            options={
                'verbose_name': 'Запись условий среды',
                'verbose_name_plural': 'Журнал условий среды',
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='Дата поступления')),
                ('receipt_signature', models.CharField(max_length=100, verbose_name='Подпись принявшего')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issue_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись выдавшего')),
                ('si', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='si.si', verbose_name='Средство измерений')),
            ],
            options={
                'verbose_name': 'Запись журнала регистрации',
                'verbose_name_plural': 'Журнал регистрации СИ',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_result', models.CharField(max_length=100, verbose_name='Результат поверки')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate', verbose_name='Свидетельство')),
                ('si', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='si.si', verbose_name='Средство измерений')),
            ],
            options={
                'verbose_name': 'Запись журнала поверки',
                'verbose_name_plural': 'Журнал поверки',
                'ordering': ['-certificate__verification_date'],
            },
        ),
    ]
