# Generated by Django 5.1.7 on 2025-04-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalsJournalenvironment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measurement_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Запись условий среды',
                'verbose_name_plural': 'Журнал условий среды',
                'db_table': 'journals_journalenvironment',
                'ordering': ['-measurement_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalsJournalregistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receipt_date', models.DateField()),
                ('receipt_signature', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issue_signature', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Запись журнала регистрации',
                'verbose_name_plural': 'Журнал регистрации СИ',
                'db_table': 'journals_journalregistration',
                'ordering': ['-receipt_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalsJournalverification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verification_result', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Запись журнала поверки',
                'verbose_name_plural': 'Журнал поверки',
                'db_table': 'journals_journalverification',
                'ordering': ['-certificate__verification_date'],
                'managed': False,
            },
        ),
    ]
